第９章　チェック演習

In [2]:
# チェック演習9-1：「numpy」の次の①～③の表示形式を設定する。
# ① 固定小数点表示、② 小数点以下3桁、③ 最終桁が0でも明示的に表示

# numpyのインポート
import numpy as np

# 表示形式を設定
np.set_printoptions(
    suppress=True, precision=3, floatmode='fixed'
)

In [3]:
# チェック演習9-2：
# (1) 行番号 i=0 ,1,2,3, 列番号 j=0,1,2,3,4 で、要素の数値が(i+1)×(j+1)の4行5列数値データ(ndarray)を作る。
# 4x5のゼロ埋め配列を作成
array92 = np.zeros((4, 5))
# forループを使って各要素に値を計算して入れる
for i in range(array92.shape[0]):      # shape[0]で行を指定し、4行分（0, 1, 2, 3）をループする
                                       # 参考: [for i, row in enumerate(array92):]とすれば、各行データ(row)が利用可能
    for j in range(array92.shape[1]):  # shape[1]で列を指定し、5列分（0, 1, 2, 3, 4）をループする
        array92[i, j] = (i+1) * (j+1)  # 計算を行う
print(array92)

# (2) データの性質（データの型, 要素の型, 行列の形, 行数）を確認する
print('type =', type(array92))
print('dtype =', array92.dtype)
print('shape =', array92.shape)
print('len =', len(array92))

[[ 1.000  2.000  3.000  4.000  5.000]
 [ 2.000  4.000  6.000  8.000 10.000]
 [ 3.000  6.000  9.000 12.000 15.000]
 [ 4.000  8.000 12.000 16.000 20.000]]
type = <class 'numpy.ndarray'>
dtype = float64
shape = (4, 5)
len = 4


In [4]:
# チェック演習9-3：
# (1) Linspace関数で、始点=0, 終点=100, 等間隔点数=5で等分割する。
n93L = np.linspace(0, 100, 5)
print(n93L)

# (2) arange関数で、始点=0, 終点=100, 等間隔値=10で等分割する。
n93A = np.arange(0, 100, 25)       # arange関数終点を含まないことに注意！
print(n93A)

[  0.000  25.000  50.000  75.000 100.000]
[ 0 25 50 75]


In [5]:
# チェック演習9-4：コード9.4.1のn44でスライス抽出する。
# コード9.4.1のn44をarray関数で定義
n44 = np.array([
    [ 2,  4,  6,  8],
    [10, 12, 14, 16],
    [18, 20, 22, 24],
    [26, 28, 30, 32]
])
print(n44)

# スライス（抽出）
n22 = n44[1:3, 1:3]
print(n22)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
[[12 14]
 [20 22]]


In [6]:
# チェック演習9-5：
# コード9.4.1のn44で、列のインデックスにブール値[True, True, False, False]を指定し、True列を取り出す。
# 列インデックスに、True/False指定して、列を取り出す
n95_column = np.array([True, True, False, False])
n95 = n44[ : , n95_column]

print(n95)
print(n95.shape)

[[ 2  4]
 [10 12]
 [18 20]
 [26 28]]
(4, 2)


In [7]:
# チェック演習9-6：
# コード9.5.1のm1, m2 の引き算、掛け算、割り算、を行い、結果を確認する。
# 演算対象のnumpy変数定義
m1 = np.array([ [ 0, 1, 2], [3, 4, 5] ])
m2 = np.array([ [ 5, 4, 3], [2, 1, 0] ])

print(m1)
print(m2)

m1_m2 = m1 - m2
print('m1 - m2: ')
print(m1_m2)

m1Tm2 = m1 * m2
print('m1 * m2: ')
print(m1Tm2)

m1Dm2 = m1/m2
print('m1 / m2: ')
print(m1Dm2)

[[0 1 2]
 [3 4 5]]
[[5 4 3]
 [2 1 0]]
m1 - m2: 
[[-5 -3 -1]
 [ 1  3  5]]
m1 * m2: 
[[0 4 6]
 [6 4 0]]
m1 / m2: 
[[0.000 0.250 0.667]
 [1.500 4.000   inf]]


/tmp/ipython-input-577437056.py:18: RuntimeWarning: divide by zero encountered in divide
  m1Dm2 = m1/m2


In [8]:
# チェック演習9-7（ブロードキャスト機能）：

#(1)【機能A】次元数の多い配列の形状にあわせて次元数を整える。
# 図に示す演算を行い、機能Aを確かめる。

# スカラーと配列の演算
a = 10                   # スカラー値
b = np.array([1, 2, 3])  # 形状: (,3)
c = a + b                # 結果の形状: (,3)
print('機能A：次元数を整える')
print(c)

# (2)【機能B】サイズが1次元の配列は、他方の配列の対応する次元のサイズに合わせて拡張される。
# ただし、1次元配列（行ベクトルまたは列ベクトル）の要素数は、他の配列と同じ(行数または列数が同じ）でなければならない。
# 図に示す演算を行い、機能Bを確かめる。
# 列ベクトルと行列の演算

a = np.array([[10], [20], [30]])                    # 形状: (3, 1)
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])     # 形状: (3, 3)
c = a + b                                      # 結果の形状: (3, 3)
print('機能B：次元数の拡張')
print(c)

機能A：次元数を整える
[11 12 13]
機能B：次元数の拡張
[[11 12 13]
 [24 25 26]
 [37 38 39]]


In [9]:
# チェック演習9-8（ユニバーサル関数）：
# チェック演習9-7の機能Bで用いた行列bの全要素を指数計算し、さらに対数計算することで、元の行列に戻ることを確かめる。
c = np.exp(b)
print(c)

d = np.log(c)
print(d)

[[   2.718    7.389   20.086]
 [  54.598  148.413  403.429]
 [1096.633 2980.958 8103.084]]
[[1.000 2.000 3.000]
 [4.000 5.000 6.000]
 [7.000 8.000 9.000]]


In [10]:
# チェック演習9-9：
# チェック演習9-7の機能Bで用いた行列bの各列の平均値を計算し、各列からそれそれの列平均値を引いた行列を計算する。

# 行列の再定義
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ave1 = np.average(b, axis=1)    # 各列の平均値を計算(axis=1で列方向指定)
c = b - ave1        # 各列から平均値を引く
print('行列b ')
print(b)
print('列平均値 = ', ave1)
print('行列b - 列平均値')
print(c)

行列b 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
列平均値 =  [2.000 5.000 8.000]
行列b - 列平均値
[[-1.000 -3.000 -5.000]
 [ 2.000  0.000 -2.000]
 [ 5.000  3.000  1.000]]


In [12]:
# チェック演習9-10：
# (1) チェック演習9-9の次の行列の各列ごとにmin-max正規化を行う。
# 行列の定義
b = np.array([[1, 2, 3, 4], [1, 2, 5, 6], [0, 4, 10, 15]])

# 列ごとの最小値と最大値を計算
col_min = b.min(axis=0)
col_max = b.max(axis=0)

# 正規化
normalized_b1 = (b - col_min) / (col_max - col_min)
print(normalized_b1)

# (2) Python (scikit-learn) を使う場合のプログラム
print('*** 応用：Python (scikit-learn) を使う場合 ***')
from sklearn.preprocessing import MinMaxScaler
# インスタンス作成
scaler = MinMaxScaler()
# 正規化を実行
normalized_b2 = scaler.fit_transform(b)
print(normalized_b2)

[[1.000 0.000 0.000 0.000]
 [1.000 0.000 0.286 0.182]
 [0.000 1.000 1.000 1.000]]
*** 応用：Python (scikit-learn) を使う場合 ***
[[1.000 0.000 0.000 0.000]
 [1.000 0.000 0.286 0.182]
 [0.000 1.000 1.000 1.000]]
