第9章　演習問題　解答例

NumPyの初期設定

In [ ]:
# numpyのインポート
import numpy as np

In [ ]:
# numpy表示形式の設定
# suppress=True : 固定小数点表示
# precision=4   : 小数点以下4桁
# floatmode='fixed' : 最終桁が0でも明示的に表示

np.set_printoptions(
    suppress=True, precision=4, floatmode='fixed'
)

問題９ー１

In [ ]:
# array関数による行列変数の定義
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

# 結果確認
print(n)

# ベクトル変数の性質の確認
print(type(n))
print(n.dtype)
print(n.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)


問題９－２

In [ ]:
# パターン：特定の列
n1= n[:,1]

print(n1)
print(n1.shape)

[2 5]
(2,)


問題９－３

In [ ]:
# パターン：特定の行
n2 = n[1, :]

print(n2)
print(n2.shape)

[4 5 6]
(3,)


問題９－４【ブロードキャスト機能】
問題９－１で定義した行列nの全ての要素に３を足した行列を作り、表示しなさい。

In [ ]:
# ブロードキャスト機能を使った足し算
n3 = n + 3   # ベクトル + スカラー
print('ブロードキャスト機能'); print(n3)

ブロードキャスト機能
[[4 5 6]
 [7 8 9]]


問題９－５【ユニバーサル関数機能】
問題９－１で定義した行列nの全ての要素の2乗とする行列を作り、表示しなさい。

In [ ]:
# ユニバーサル機能を使った2乗の計算（一括で計算できる）
n4 = n**2
print(n4)

[[ 1  4  9]
 [16 25 36]]


問題９－６【集約メソッド】
問題９－１で定義した行列nの列の合計と行の合計を計算し、表示しなさい。

In [ ]:
# sumメソッドでの計算
sum0 = n.sum(axis=0)
sum1 = n.sum(axis=1)

print('sum(axis=0):', sum0)
print('sum(axis=1):', sum1)

sum(axis=0): [5 7 9]
sum(axis=1): [ 6 15]


問題９－７

In [ ]:
# パターン：転置行列
n5 = np.transpose(n)

print(n5)
print(n5.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [ ]:
#行列のかけ算
n6 = np.matmul(n, n5)

print(n6)
print(n6.shape)

[[14 32]
 [32 77]]
(2, 2)


問題９－８
ベクトルv=[1,2,3], w=[4,5,6] の内積を求めなさい。

In [ ]:
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

print(np.inner(v, w))

32


問題９－９
ベクトルv=[1,2,3], w=[4,5,6] の外積を求めなさい。

In [ ]:
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

print(np.cross(v, w))

[-3  6 -3]


問題９－10
np.array([[1,2],[3,4]])で定義した行列の逆行列を求めなさい。

In [ ]:
n7 = np.array([
    [1,2],[3,4]
])
n7i = np.linalg.inv(n7)
print(n7i)

[[-2.0000  1.0000]
 [ 1.5000 -0.5000]]


問題９－11
行列n7とその逆行列を掛けて単位行列になることを確認しなさい。

In [ ]:
#行列のかけ算
n8 = np.matmul(n7, n7i)

print(n8)

[[1.0000 0.0000]
 [0.0000 1.0000]]


問題９－12
問題９－10で定義した行列の対角成分を抽出しなさい。


In [ ]:
n9 = np.diag(n7)
print(n9)

[1 4]


問題９－13
3行3列の単位行列を作りなさい。

In [ ]:
I3 = np.eye(3)
print(I3)

[[1.0000 0.0000 0.0000]
 [0.0000 1.0000 0.0000]
 [0.0000 0.0000 1.0000]]
