第９章　numpy入門

9.1　numpyの概要

In [1]:
# コード9.2,1 numPyのインポート

import numpy as np

9.2　numpy使用の準備

In [ ]:
# コード9.2,2 デフォルト設定でのprint関数出力結果

v1 = np.array([1/3, 1234, 0.001234567])
print(v1)

[   0.3333 1234.0000    0.0012]


In [ ]:
# コード9.2,3 numpy変数の表示設定
# suppress=True : 固定小数点表示
# precision=4   : 小数点以下4桁
# floatmode='fixed' : 最終桁が0でも明示的に表示

np.set_printoptions(
    suppress=True, precision=4, floatmode='fixed'
)

print(v1)

[   0.3333 1234.0000    0.0012]


9.3　numpyデータの定義



In [ ]:
# コード9.3.1　array関数によるベクトル変数の定義とその性質
# array関数によるベクトル変数の定義
v2 = np.array([0, 11, 22, 33])

# 結果確認
print(v2)

# ベクトル変数の性質の確認
print('type =', type(v2))
print('dtype =', v2.dtype)
print('shape =', v2.shape)
print('len =', len(v2))

[ 0 11 22 33]
type = <class 'numpy.ndarray'>
dtype = int64
shape = (4,)
len = 4


In [ ]:
# コード9.3.2　array関数による行列変数の定義とその性質
# array関数による行列変数の定義
m1 = np.array([
    [ 0,  1,  2,  3],
    [10, 11, 12, 13],
    [20, 21, 22, 23],
])

# 結果確認
print(m1)

# ベクトル変数の性質の確認
print('type =', type(m1))
print('dtype =', m1.dtype)
print('shape =', m1.shape)
print('len =', len(m1))

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
type = <class 'numpy.ndarray'>
dtype = int64
shape = (3, 4)
len = 3


In [ ]:
# 9.3.3　linspace関数による等間隔分割
# 引数は（始点, 終点, 等間隔点数）
n3 = np.linspace(0, 1, 6)

# arange関数による等間隔分割
# 引数は（始点, 終点, 等間隔値）※区間に終点を含まない
n4 = np.arange(0, 1, 0.2)

# 結果確認
print('linespace関数による(0, 1, 6)の等間隔分割：', n3)
print('arange関数による(0, 1, 0.2)の等間隔分割： ', n4)

linespace関数による(0, 1, 6)の等間隔分割： [0.0000 0.2000 0.4000 0.6000 0.8000 1.0000]
arange関数による(0, 1, 0.2)の等間隔分割：  [0.0000 0.2000 0.4000 0.6000 0.8000]


9.4　ベクトルおよび行列データの要素参照（スライス）

In [ ]:
# コード9.4.1
# array関数による行列変数の定義
m44 = np.array([
    [ 2,  4,  6,  8],
    [10, 12, 14, 16],
    [18, 20, 22, 24],
    [26, 28, 30, 32]
])
print(m44)

# パターン１：スカラー（一つの要素）
m44_1 = m44[1, 2]
print('m44 [1, 2] = ', m44_1)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
m44 [1, 2] =  14


In [ ]:
# パターン２：特定の行
m44_2 = m44[1,:]

print('m44[1,:] = ', n5)
print( m44_2.shape)

m44[1,:] =  [10 12 14 16]
(4,)


In [ ]:
# パターン３：特定の行の一部
m44_3 = m44[1,1:3]

print('m44[1,1:3] = ', m44_3)
print(m44_3.shape)

m44[1,1:3] =  [12 14]
(2,)


In [ ]:
# パターン４：特定の列
m44_4 = m44[:,1]

print('m44[:,1] = ', m44_4)
print(m44_4.shape)

m44[:,1] =  [ 4 12 20 28]
(4,)


In [ ]:
# パターン５：特定の列の一部
m44_5 = m44[1:3, 1]

print('m44[1:3, 1] = ', m44_5)
print(m44_5.shape)

m44[1:3, 1] =  [12 20]
(2,)


In [ ]:
# パターン６：特定の行列
m44_6 = m44[1:3,2:]

print('m44[1:3,2:] = '); print(m44_6)
print(m44_6.shape)

m44[1:3,2:] = 
[[14 16]
 [22 24]]
(2, 2)


In [ ]:
# コード9.4.2　行列型データの要素参照（True/False）
# 行インデックスに、True/False指定して、行を取り出す
m44_row = np.array([True, False, True, False])
m44_rTF = m44[m44_row, :]   #　m44_rTF = m44[m44_row]でもよい

print(m44_rTF)
print(m44_rTF.shape)

[[ 2  4  6  8]
 [18 20 22 24]]
(2, 4)


In [ ]:
# 列インデックスに、True/False指定して、列を取り出す
m44_column = np.array([True, False, True, False])
m44_cTF = m44[: , m44_column]

print(m44_cTF)
print(m44_cTF.shape)

[[ 2  6]
 [10 14]
 [18 22]
 [26 30]]
(4, 2)


9.5　行列型データの演算

In [ ]:
# コード 9.5.1 行列の足し算
# 演算対象のNumPy変数定義
m1 = np.array([ [ 0, 1, 2], [3, 4, 5] ])
m2 = np.array([ [ 5, 4, 3], [2, 1, 0] ])

print(m1)
print(m2)

# 行列の足し算
m3 = m1 + m2
print('2つの行列 m1 + m2 = ')
print(m3)

[[0 1 2]
 [3 4 5]]
[[5 4 3]
 [2 1 0]]
2つの行列 m1 + m2 = 
[[5 5 5]
 [5 5 5]]


In [ ]:
# コード 9.5.2 ブロードキャスト機能を使った足し算
# 演算対象のnumpy変数定義
v1 = np.array([ 0, 1, 2])
m1 = np.array([ [ 0, 1, 2], [3, 4, 5] ])
v2 = np.array([ 6, 7, 8])
print(v1)
print(m1)
print(v2)

# ブロードキャスト機能を使った足し算
v3 = v1 + 2   # ベクトル + スカラー
m4 = m1 + v2  # 行列 + ベクトル
print('ブロードキャスト機能(A):  v1 + 2  '); print(v3)
print('ブロードキャスト機能(B):  m1 + v2 '); print(m4)

[0 1 2]
[[0 1 2]
 [3 4 5]]
[6 7 8]
ブロードキャスト機能(A):  v1 + 2  
[2 3 4]
ブロードキャスト機能(B):  m1 + v2 
[[ 6  8 10]
 [ 9 11 13]]


In [ ]:
# コード 9.5.3 ユニバーサル関数を使ったsqrtの計算
# 演算対象のnumpy変数定義
v1 = np.array([ 0, 1, 2])

# 組込関数 math.sqrt による計算(各要素に適用する必要がある)
import math
v4 = []
for i in range(len(v1)):
    x = math.sqrt(v1[i])
    v4.append(x)
print('組込関数 math.sqrtによる繰返計算 ', v4)

# ユニバーサル関数を使った sqrtの計算（一括で計算できる）
v5 = np.sqrt(v1)
print('ユニバーサル関数を使ったsqrt計算 ', v5)

組込関数 math.sqrtによる繰返計算  [0.0, 1.0, 1.4142135623730951]
ユニバーサル関数を使ったsqrt計算  [0.0000 1.0000 1.4142]


In [ ]:
# コード 9.5.4 集約メソッド（sum関数）
# 演算対象のnumpy変数定義
m2 = np.array([ [ 0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11] ])
print(m2)

# sum関数の計算
sum0 = m2.sum(axis=0)
sum1 = m2.sum(axis=1)
sum2 = m2.sum()
print('sum(axis=0):', sum0)
print('sum(axis=1):', sum1)
print('sum():      ', sum2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
sum(axis=0): [12 15 18 21]
sum(axis=1): [ 6 22 38]
sum():       66


比較演算子の行列データへの適用

In [11]:
# コード 9.5.5 行列データの比較
# 演算対象の2つのnumpy変数定義
m3 = np.array([ [ 0, 1, 2], [3, 4, 5], [6, 7, 8] ])
m4 = np.array([ [ 1, 2, 2], [3, 4, 4], [5, 7, 8] ])
print(m3)
print(m4)

# m3とm4の各要素が一致しているか調べる
print('2つの行列の各要素が一致しているか比較')
m5 = (m3 == m4)
print(m5)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 2]
 [3 4 4]
 [5 7 8]]
2つの行列の各要素が一致しているか比較
[[False False  True]
 [ True  True False]
 [False  True  True]]


In [13]:
# コード 9.5.6 行列データとスカラー値の比較
# 演算対象のnumpy変数定義
m3 = np.array([ [ 0, 1, 2], [3, 4, 5], [6, 7, 8] ])
n = 4    # 比較するスカラー値
print(m3)
print('n = ', n)
# m3の各要素がnより大きいか調べる
print('行列の各要素がnより大きいか比較')
m6 = m3 > n
print(m6)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
n =  4
行列の各要素がnより大きいか比較
[[False False False]
 [False False  True]
 [ True  True  True]]


In [14]:
# コード 9.5.7　ブール値の集約計算
# sum関数の計算
sum_ax0 = m6.sum(axis=0)     # 列方向の集約計算
sum_ax1 = m6.sum(axis=1)     # 行方向の集約計算
sum_ax  = m6.sum()           # 全要素の集約計算
print(m6)
print('列方向のTrueの合計：sum(axis=0):', sum_ax0)
print('行方向のTrueの合計：sum(axis=1):', sum_ax1)
print('全要素のTrueの合計：sum():      ', sum_ax)

[[False False False]
 [False False  True]
 [ True  True  True]]
列方向のTrueの合計：sum(axis=0): [1 1 2]
行方向のTrueの合計：sum(axis=1): [0 1 3]
全要素のTrueの合計：sum():       4


9.6　データ分析基礎への演算応用例

In [ ]:
# コード 9.6.1 min-max正規化
# 元変数
xi = np.array([2, 5, 8, 9, 3, 11])
print('xi =', xi)

# 最大値と最小値を集約メソッドで取得
x_max = xi.max()
x_min = xi.min()
print('x_max =', x_max, '  x_min =', x_min)

# min-maxスケーリング(ブロードキャスト機能の利用)
yi = (xi - x_min) / (x_max - x_min)
print('yi =', yi)

xi = [ 2  5  8  9  3 11]
x_max = 11   x_min = 2
yi = [0.0000 0.3333 0.6667 0.7778 0.1111 1.0000]


In [ ]:
# コード 9.6.2 ブール値（True/False）を使ったデータの一致度
# 元変数
s1 = np.array(['apple', 'orange', 'cherry', 'banana', 'grape'])
s2 = np.array(['apple', 'orange', 'cherry', 'banana', 'prune'])
print('s1 =', s1)
print('s2 =', s2)

# 一致の調査
s3 = (s1 == s2)
print('一致の状態 s3 =', s3)

s1 = ['apple' 'orange' 'cherry' 'banana' 'grape']
s2 = ['apple' 'orange' 'cherry' 'banana' 'prune']
一致の状態 s3 = [ True  True  True  True False]


In [ ]:
# 一致の状態s3にsumメソッドをかけ、一致数をカウントする
# 対象変数がブール値の場合、sum関数でTrue→1, False→0 に変換し合計する
nmatch = s3.sum()

# データ数はlen(s3)で計算可能
ndata = len(s3)

# 一致度[%]の計算
dmach = nmatch/ndata*100

print('一致数: ', nmatch, '/  データ数: ', ndata,    '/  一致度[%]: ', dmach)

一致数:  4 /  データ数:  5 /  一致度[%]:  80.0
